name: Build and Push
on:
  push: {}
  workflow_dispatch: {}

jobs:
  build-with-docker:
    name: Build and push image
    runs-on: ubuntu-24.04
    steps:
      - name: Login to the registy
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.REGISTRY_URL }}/mfeder/example-app:latest
